### ISSUE TITLE
allowedHeadgear file will not save added classnames UPDATED ---> I figured it out

### ISSUE THREAD

**Issue by Savy022** [gruppe-adler/grad_slingHelmet#15]
Hey, I have added a list of helmet classnames to the allowedHeadgear.hpp file and for some reason, it will not allow me to save the file with the added info. The file will save and I will close it, but when I reopen it, everything that I had added will not be there. I use Notepad++ if that helps and I am pretty new to the world of coding sooo yeah ;)

**Comment by DerZade** [comment]
@Savy022 I'm not really sure what you tried to achieve, but you should not be able to edit the `allowedHeadgear.hpp` inside the pbo. If you did that anyways just note, that this is not the intended way of adding Headgear to the whitelist.
