### ISSUE TITLE
Adding a Headgear to the Whitelist via CBA Setting

### ISSUE THREAD

**Issue by 10Dozen** [gruppe-adler/grad_slingHelmet#3]
Hi,
is it possible to add CBA settings with additional whitelist (that will be added to core mod's whitelist)? You are using ACE dependency, so CBA is not a problem, i guess.

The code should look like (tested in mission - looks ok):

```
[ 
 "GRAD_slingHelmet_additionalList" 
 , "EDITBOX" 
 , ["Additional whitelist", "Custom additional whitelist of headgear (for SP or Server only)"] 
 , "GRAD Sling Helmets" 
 , "" 
 , true 
 , { 
     if !(isServer) exitWith {};
     GRAD_slingHelmet_whitelist = nil; 
     [] call GRAD_slingHelmet_fnc_whitelist;   
     GRAD_slingHelmet_whitelist = GRAD_slingHelmet_whitelist + call compile format ["[%1]", _this]; 
     publicVariable "GRAD_slingHelmet_whitelist";    
 } 
] call CBA_Settings_fnc_init;
```

May be added both in mission script and mod version.

Looks something like this:
https://i.imgur.com/LmdEIcV.jpg
https://i.imgur.com/q9OtRLT.jpg
https://i.imgur.com/Kbilhgv.jpg

**Comment by DerZade** [comment]
First of all, thanks for the suggestion.
If you're just looking for an option to add additional helmets to the whitelist, you may want to look at [this](https://github.com/DerZade/grad_slinghelmet/wiki/GRAD_slingHelmet_fnc_addHelmetToWhitelist).

But I'll think about adding a CBA Setting in addition to the function.
