### ISSUE TITLE
[BUG] Mod causes Linux Dedicated Server to crash on startup

### ISSUE THREAD

**Issue by david-kalbermatten** [gruppe-adler/grad_slingHelmet#38]
This is by far not the only mod that does that but it seems that some mods use the windows file path separator symbols somewhere (hardcoded). 

```bash
ErrorMessage: Cannot open file '/serverdata/serverfiles/@GRADSlingHelmets\addons\grad_slinghelmet_main'
```

**Comment by dedmen** [comment]
Its because the pbo is not lowercase only. Unrelated to windows path seperators.
pbo's need to be lowercase.

**Comment by david-kalbermatten** [comment]
So it's packaged incorrectly then...
Well, I now know at least how to fix it, thx :D
