### ISSUE TITLE
Use CBA Preinit for addon options 

### ISSUE THREAD

**Issue by Ultradar** [gruppe-adler/grad_slingHelmet#44]
Currently addon options are added Postinit. This means that settings are not available in 3den. 

Preinit would allow for these settings to be defined with a preset, rather than having to load the mission, then change the settings (Or setting it on the server). 

https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System

**Comment by DerZade** [comment]
Can you try and see if this fixes the issue for you?

[grad_slingHelmet_1.4.0.zip](https://github.com/gruppe-adler/grad_slingHelmet/files/13931959/grad_slingHelmet_1.4.0.zip)

**Comment by Ultradar** [comment]
Unfortunately not, still can only see this when playing, not in Eden. 

![image](https://github.com/gruppe-adler/grad_slingHelmet/assets/82441565/972ddb63-c108-4412-a6b2-bbce4663200c)

**Comment by DerZade** [comment]
Was worth a shot to try the easy solution 😅 

Now I'm trying the way, which is recommended by CBA. I currently have no setup to test this ingame, so I hope it even works at all :)

[grad_slingHelmet_1.4.0.zip](https://github.com/gruppe-adler/grad_slingHelmet/files/13936601/grad_slingHelmet_1.4.0.zip)

**Comment by Ultradar** [comment]
That's worked, thank you!

**Comment by OverlordZorn** [comment]
Is this fixed? will this be pushed to the steam workshop version one day?

**Comment by DerZade** [comment]
@OverlordZorn Apparently not 😅 

I released it just now in v1.4.1
